### ISSUE TITLE
Helm Integration?

### ISSUE THREAD

**Issue by gorantornqvist-sr** [rancher/terraform-null-rke2-install#159]
Hi,
I cant see any way to put HelmChart or HelmChartConfig manifests in /var/lib/rancher/rke2/server/manifests with this module?

**Comment by gorantornqvist-sr** [comment]
If we want to install another CNI like Cilium Enterprise we need to set cni: none and pass a custom HelmChart and values ...

**Comment by matttrach** [comment]
Thank you so much for sharing!
I have added https://github.com/rancher/terraform-null-rke2-install/commit/d9352d3da2ec4956e11d90dea095f2b819f81b3d to enable this use case.

**Comment by matttrach** [comment]
I also added an example of using the new feature to deploy a custom cilium chart, hopefully this gives you a jump up on the process. Our examples are used directly in our tests, so this will also serve as an acceptance test for your use case.
Please open a new issue if there is anything else I can do!
https://github.com/rancher/terraform-null-rke2-install/tree/main/examples/manifest
